export { generateUniqueKey as generateParticipantKey } from '@conference/key-utils'
export { generateKeyFromName as generateKeyFromParticipant } from '@conference/key-utils'
export { isValidKey as isValidParticipantKey } from '@conference/key-utils'
export { splitName } from '@conference/key-utils'
export type { KeyInput as ParticipantKeyInfo } from '@conference/key-utils'
